//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperExcitingCloneEffect.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperExcitingCloneEffect.Properties.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   [E01]CommandListが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exception_CommandListIsNull {
            get {
                return ResourceManager.GetString("Exception_CommandListIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_CloneGroupValue {
            get {
                return ResourceManager.GetString("GroupName_CloneGroupValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クローン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupName_CloneValue {
            get {
                return ResourceManager.GetString("GroupName_CloneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クローン個別エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IManagedItem_CloneEffects {
            get {
                return ResourceManager.GetString("IManagedItem_CloneEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IManagedItem_Comment {
            get {
                return ResourceManager.GetString("IManagedItem_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループ内のクローン個別エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IManagedItem_GroupEffects {
            get {
                return ResourceManager.GetString("IManagedItem_GroupEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IManagedItem_Hide {
            get {
                return ResourceManager.GetString("IManagedItem_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名札 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IManagedItem_NameTag {
            get {
                return ResourceManager.GetString("IManagedItem_NameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin_Category {
            get {
                return ResourceManager.GetString("Plugin_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   超☆エキサイティン複製エフェクト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin_Name {
            get {
                return ResourceManager.GetString("Plugin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   超エキサイティン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Plugin_Tag_1 {
            get {
                return ResourceManager.GetString("Plugin_Tag_1", resourceCulture);
            }
        }
    }
}
